import time
import os
from datetime import datetime
opentime = datetime.now().time()
print('Initalizing setup...')
time.sleep(2)
s1 = open('config.config', "w")
s1.write('localhost = 1\nscripts = scripts\nstart.config\nonlocal=0\nlocalToken="33434An3ikNm3am"\na4a4a4a4a4a4a4a4a4a4a4a4a\ns--------------------------\nbreak()')
s1.close()
print('Config file successfully written.')
time.sleep(1)
print('creating EZlog file...')
s2 = open('EZlog', "w")
s2.write('# log setup\nlogSetup = true\nnil\n')
s2.close()
time.sleep(2)
s3 = open('EZsetvar', 'w')
s3.write('var=1\nvar2\nvar3\nYou shouldnt be reading this file xd')
s3.close()
print('Setting variables..')
time.sleep(2)
print('Creating Directories..')
os.mkdir('EZpack1')
os.mkdir('EZpack2')
os.mkdir('EZpack3')
os.mkdir('EZpack4')
os.mkdir('EZpack5') #Creates Different Packages.
os.mkdir('logKeeper') # The directory that keeps log files
time.sleep(5)
print('Writing config...')
con = open('config.config', "w")
con.write('config.rewrite = true\nEZpack1\nEZpack2\nEZpack3\nEZpack4\nEZpack5\nEZlog\n')
con.close()
time.sleep(0.90)
print('config file rewritten.')
time.sleep(0.50)
print('Initalizing Final Setup..')
coc = open('config.config', "a")
coc.write('config.files.start = 1')
coc.close()

time.sleep(3)
print('Setup Complete! Say ezsetup log for what files were made/deleted')
setchance = input('>_')
if setchance.strip() == 'ezsetup log':
    print(opentime)
    print('created config.config')
    print(opentime)
    print('created EZLog File.')
    print(opentime)
    print('Created EZsetvar')
    print(opentime)
    print('Set 6 Packages, EZpack1 EZpack2 EZpack3 EZpack4 EZpack5 LogKeeper')

elif setchance.strip() == '':
    print('exiting...')
time.sleep(0.60)

print('Exit slip')
exit = input('>')